### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by zhangzhenhu** [rgtjf/Semantic-Texual-Similarity-Toolkits#16]
File "Semantic-Texual-Similarity-Toolkits-master/stst/libs/kernel/tree_kernels.py", line 498, in evaluate
    (m,match) = self.mergetrees_with_depth_del_labels(tree1, tree2)

TypeError: mergetrees_with_depth_del_labels() missing 2 required positional arguments: 'tree2' and 'labels2'

**Comment by rgtjf** [comment]
Thanks for your report. It may be BUG. I will have a look when I have time.

I think it may caused by the wrong parse tree format into the tree_kernel. You could test it in ``https://github.com/rgtjf/Semantic-Texual-Similarity-Toolkits/blob/master/stst/libs/kernel/test_tree_kernels.py``
