### ISSUE TITLE
It seems that make_feature_file didn't write #instances, #dimension to feature file

### ISSUE THREAD

**Issue by linus-young** [rgtjf/Semantic-Texual-Similarity-Toolkits#8]
`print(str(len(train_instances)) + ' ' + str(merged_feature_dimension), file=f_feature)` didn't work

**Comment by rgtjf** [comment]
You can check the file ``make_feature_files`` in  ``stst/model.py`` .

**Comment by linus-young** [comment]
Yep, I checked it and tried to fix it by adding the aforementioned line, but still no header
